<?php	$address       = $this->getRequest()->getPost('address');
	$state_or_stub = $this->getRequest()->getPost('state_or_stub');
	$zipcode       = $this->getRequest()->getPost('zipcode');
	
	$search_add   = Mage::getStoreConfig('igex/search_options/search_by_address'); 
	$search_state = Mage::getStoreConfig('igex/search_options/search_by_state'); 
	$search_zip   = Mage::getStoreConfig('igex/search_options/search_by_zipcode'); 
	$search_rad   = Mage::getStoreConfig('igex/search_options/search_by_radius'); 
        $show_state   = Mage::getStoreConfig('igex/search_options/state_search'); 
	$show_img     = Mage::getStoreConfig('igex/display_options/show_image'); 
	$show_email   = Mage::getStoreConfig('igex/display_options/show_email_and_website');
	$show_ph      = Mage::getStoreConfig('igex/display_options/show_phone');	?>

<div class="page-title">
	<h1><?php echo $this->__('Store Locator');?></h1>
</div>
<div class="str_add_box">
  <?php 
  		$speacialStoreAll = Mage::getModel('igex_storelocator/store')->getCollection()
					  ->addFieldToFilter('status',1)
					  ->addFieldToFilter('topvisible',1);

  foreach($speacialStoreAll as $specialStore):
  	if(!is_null($specialStore->getImage()) || $specialStore->getImage() != ''){
                $imgUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$specialStore->getImage();
            }elseif (!is_null(Mage::getStoreConfig('igex/storelocator_options/defaultimage')) && Mage::getStoreConfig('igex/storelocator_options/defaultimage') != ''){
                $imgUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'storelocator/images/'.Mage::getStoreConfig('igex/storelocator_options/defaultimage');
            }else{
                $imgUrl = $this->getLogoSrc();
            }
            $specialStore->setImage($imgUrl);
  ?>
    <div class="str_add_box_lft">
      <div class="str_add_left"><img src="<?php echo $specialStore->getImage(); ?>" width="185" height="150" alt="<?php echo $specialStore->getName(); ?>" /></div>
      <div class="str_add_right">
           <div class="str_add_right_head"><?php echo $specialStore->getName(); ?></div>
        <div class="str_add_txt">
          <ul>
            <li><?php echo nl2br($specialStore->getAddress()); ?></li>
            <li><?php echo $specialStore->getState()." ".$specialStore->getZipcode(); ?></li>
          </ul>
          <div class="add_tel"><?php if(!is_null($specialStore->getPhone())&& $specialStore->getPhone()!= ''):?>
              <?php echo $this->__('T : %s', $specialStore->getPhone()); ?>
              <?php endif; ?></div>
        </div>
      </div>
    </div>
   <?php endforeach; ?>
  </div><div style="clear:both;"></div><br/>

<h3 class="legend" style="<?php if($search_rad==0 && $search_add==0 && $search_zip==0 && $search_state==0):?>display:none;<?php endif;?>"><?php echo $this->__('Search By:') ?></h3>

<form action="<?php echo Mage::getUrl('igex_storelocator/'); ?>" method="post">
<div id="search" style="<?php if($search_add==0):?>display:none;<?php endif;?>">
        <label for="address" class="label"><?php echo $this->__('Address : ');?></label>
        <input type="text" class="igex_input_box" name="address" id="address" value="<?php echo $address; ?>" />
</div>

<div id="search" style="<?php if($search_state==0):?>display:none;<?php endif;?>">
	<label for="state" class="label"><?php echo $this->__('State : ');?></label>
	<input type="text" class="igex_input_box" name="state_or_stub" id="state_or_stub" value="<?php echo $state_or_stub; ?>" />
</div>

<div id="search" style="<?php if($search_zip==0 && $search_rad==0):?>display:none;<?php endif;?>">
	<label for="zipcode" class="label"><?php echo $this->__('Zipcode : ');?></label>	
	<input type="text" class="igex_input_box" value="<?php echo $zipcode; ?>" name="zipcode" id="zipcode" />
</div>

<div id="search" style="<?php if($search_rad==0):?>display:none;<?php endif;?>">
<?php $searchRadiusOptions = Mage::helper('igex_storelocator')->getSearchRadiusOptions();?>
<?php if(count($searchRadiusOptions)):?>
	<label for="radius"  class="label"><?php echo $this->__('Search Radius :') ?></label>
	<select name="radius" id="radius" class="igex_input_box">
		<?php foreach ($searchRadiusOptions as $option):?>
		<option value="<?php echo $option['value'] ?>" <?php if ($option['value'] == Mage::helper('igex_storelocator')->getSearchRadius()):?> selected<?php endif;?>><?php echo $option['label']?> </option>
		<?php endforeach;?>
	</select>
<?php endif;?>
</div>
<div id="search" style="<?php if($search_rad==0 && $search_add==0 && $search_zip==0 && $search_state==0):?>display:none;<?php endif;?>">
<button type="submit" title="<?php echo $this->__('Search') ?>" name="search" class="button"><span><span><?php echo $this->__('Search') ?></span></span></button>

<button type="button" onclick="setLocation('<?php echo $this->getUrl('igex_storelocator')?>')" class="button" title="<?php echo $this->__('Reset') ?>"><span><span><?php echo $this->__('Reset') ?></span></span></button>
</div>
</form>
</div>

<div id="maps">
    <div id="map_canvas" style="height:400px;width:880px;"></div>
</div>
<div id="panel"></div>
<div class="st_link">
    <ul>
    <?php

	if($show_state==1)
	{
		$stateLink = Mage::getModel('igex_storelocator/store')->getCollection()
					  ->addFieldToFilter('status',1)
					  ->addFieldToSelect(array('state'));
		$stateArr = array();
		foreach($stateLink as $state){
			if($state['state'] && !(in_array($state['state'],$stateArr))){
				$stateArr[] = $state['state'];
				array_unique($stateArr);
			}
		}
		arsort($stateArr);
		
		for($x=0;$x<count($stateArr);$x++){
		$cls='';	
			if($stateReq!='' && $stateReq== $stateArr[$x]){ $cls = 'class="active"'; }
			else if($stateReq=='' && $zipcode=='' && $state_or_stub=='' && $x==0){ $cls = 'class="active"'; }
	?>
      <li <?php echo $cls; ?>><a href="<?php echo Mage::getUrl('igex_storelocator/',array('state'=>$stateArr[$x])); ?>"><?php echo $stateArr[$x]; ?></a></li>
    <?php
		}
	}
	?>
    </ul>
  </div>
<div style="clear:both;"></div>
<br/>

<!--<?php echo count($this->getStores()); ?>-->
<h3><?php echo $this->__('All Stores ('.count($this->getStores()).')');?></h3>
    
<!--<?php echo $this->getPagerHtml();?>-->
<table class="data-table" id="store-table">
			<colgroup>
				<col>
				<col>
				<col width="130px">
				<?php if($show_email==1): ?>
				<col width="1">
				<col width="1">
				<?php endif; ?>
			</colgroup>
			<thead>
				<tr>
					<th><?php echo $this->__('Store') ?></th>
					<th><?php echo $this->__('Address') ?></th>
					<?php if($show_ph==1): ?>
					<th><?php echo $this->__('Phone') ?></th>
					<?php endif; ?>
					<?php if($show_email==1): ?>
					<th><?php echo $this->__('Email') ?></th>
					<th><?php echo $this->__('Website') ?></th>
					<?php endif; ?>
				</tr>
			</thead>
			<tbody>
			<?php $all = $this->getCollection();?>
				<?php foreach($all as $store) :?>
				<tr>
					<td style="cursor: pointer;" id="store<?php echo $store->getId() ?>"><?php echo $store->getName()?></td>
					<td><?php echo $store->getAddress()." ".$store->getZipcode()?></td>
					<?php if($show_ph==1): ?>
					<td><?php echo $store->getPhone()?></td>
					<?php endif; ?>
					<?php if($show_email==1): ?>
					<td><?php echo $store->getEmail()?></td>
					<td><?php echo $this->__("<a href='".$store->getStoreUrl()."' target='_blank'>");?><?php echo $store->getStoreUrl()?><?php echo $this->__("</a>");?></td>
					<?php endif?>
				</tr>
				<?php endforeach;?>
			</tbody>
</table>

<?php if(count($this->getStores())==0):?>
<div class="note">There are no stores matching your selection</div>
<?php endif;?>

<script type="text/javascript">

	var state_or_stubVar = document.getElementById('state_or_stub');
	var zipcodeVar	     = document.getElementById('zipcode');
	var allowFlag	     = 0;

	function checkForm() 
	{ 
		 if(state_or_stubVar.value!=''){ allowFlag = 1; }
		 else if(zipcodeVar.value!=''){ allowFlag = 1; }	

		 if(allowFlag == 1){ return true; }
		 alert('Enter Your State Or Postcode');
		 return false;
	}
    
	var estimateDirectionLabel = '<?php echo $this->__('Calculating the estimated'); ?>';
	var gmapUrl = '<?php echo $this->getGoogleApiUrl(); ?>';
	var apiSensor = <?php echo Mage::getStoreConfig('igex/storelocator_options/apisensor'); ?>;
	var stores = <?php echo Mage::helper('core')->jsonEncode($this->getStores()->toArray()); ?>;
    	var mediaUrl = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>';
	var pathMarker = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>';
	var defaultMarker = '<?php echo $this->getDefaultMarker(); ?>';
	var directionEnable = <?php echo Mage::getStoreConfig('igex/storelocator_options/direction'); ?>;
	window.onload = loadScript;

</script>
